apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}

    http {
      upstream backend {
        # round robin by default across all internal load balancers
        server internal-sampleapp-2by2.default.svc.cluster.local:8080;
        server internal-sampleapp-2by3.default.svc.cluster.local:8080;
        server internal-sampleapp-3by2.default.svc.cluster.local:8080;
        server internal-sampleapp-6by1.default.svc.cluster.local:8080;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://backend;
        }
      }
    }
