apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-gcbench
data:
  nginx.conf: |
    events {}

    http {
      upstream backend {
        # round robin by default across all internal load balancers. 
        # Uncomment least_conn below to enable least connections
        # least_conn;
        server internal-sampleapp-ergonomics.default.svc.cluster.local:8080;
        server internal-sampleapp-g1gc.default.svc.cluster.local:8080;
        server internal-sampleapp-pgc.default.svc.cluster.local:8080;
      }

      server {
        listen 80;

        location / {
          proxy_pass http://backend;
        }
      }
    }
