apiVersion: v1
kind: Service
metadata:
  name: internal-sampleapp-all
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    service: sampleappfront
