apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp-6by1
spec:
  strategy: 
    type: Recreate
  replicas: 6
  selector:
    matchLabels:
      app: sampleapp
      version: 6by1
  template:
    metadata:
      labels:
        app: sampleapp
        version: 6by1
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: sampleapp-6by1
        image: devnexus2024.azurecr.io/sampleapp:latest
        imagePullPolicy: Always
        env:
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "InstrumentationKey=fa718877-7894-43ac-bbc2-9bbb90f25bf3;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/"
        - name: APPLICATIONINSIGHTS_ROLE_NAME
          value: "6BY1"
        - name: APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED
          value: "true"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=70"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        # readinessProbe:
        #  httpGet:
        #    path: /
        #    port: 8080
        #  timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: internal-sampleapp-6by1
  labels: 
    service: sampleappfront
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  selector:
    app: sampleapp
    version: 6by1